/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/record`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign_up` | `/sign_up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/expense` | `/expense`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/reminder` | `/reminder`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/record`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign_up` | `/sign_up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab)'}/expense` | `/expense`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab)'}/insights` | `/insights`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tab)'}/reminder` | `/reminder`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/record${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign_up${`?${string}` | `#${string}` | ''}` | `/sign_up${`?${string}` | `#${string}` | ''}` | `${'/(tab)'}/expense${`?${string}` | `#${string}` | ''}` | `/expense${`?${string}` | `#${string}` | ''}` | `${'/(tab)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tab)'}/insights${`?${string}` | `#${string}` | ''}` | `/insights${`?${string}` | `#${string}` | ''}` | `${'/(tab)'}/reminder${`?${string}` | `#${string}` | ''}` | `/reminder${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/record`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign_up` | `/sign_up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/expense` | `/expense`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tab)'}/reminder` | `/reminder`; params?: Router.UnknownInputParams; };
    }
  }
}
