/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#cac6e6",
        "outline-variant": "#acb3b4",
        "on-surface-variant": "#596061",
        "surface": "#f9f9f9",
        "surface-container-low": "#f2f4f4",
        "  tertiary": "#5f5c78",
      "background": "#f9f9f9",
        "on-error-container": "#752121",
        "on-tertiary-fixed": "#37354f",
        "on-tertiary": "#fcf7ff",
      "secondary": "#5d5f65",
        "secondary-dim": "#515359",
        "outline": "#757c7d",
        "tertiary-container": "#d8d3f4",
        "secondary-container": "#e2e2e9",
        "surface-container-highest": "#dde4e5",
        "secondary-fixed-dim": "#d4d4db",
        "on-secondary": "#f9f8ff",
        "on-background": "#2d3435",
        "on-error": "#fff7f6",
        "surface-tint": "#005bc1",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#3e3f45",
        "primary": "#005bc1",
        "primary-container": "#d8e2ff",
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed-variant": "#54516d",
        "primary-dim": "#004faa",
        "primary-fixed-dim": "#c2d4ff",
        "on-surface": "#2d3435",
        "tertiary-dim": "#53506b",
        "on-primary-container": "#004ea8",
        "error-dim": "#4e0309",
        "inverse-on-surface": "#9c9d9d",
        "error-container": "#fe8983",
        "on-secondary-fixed-variant": "#5a5b61",
        "on-tertiary-container": "#4a4863",
        "surface-container-high": "#e4e9ea",
        "on-primary-fixed-variant": "#0058bb",
        "surface-variant": "#dde4e5",
        "on-primary-fixed": "#003d85",
        "primary-fixed": "#d8e2ff",
        "inverse-surface": "#0c0f0f",
        "secondary-fixed": "#e2e2e9",
        "inverse-primary": "#4b8eff",
        "on-secondary-container": "#505157",
        "tertiary-fixed": "#d8d3f4",
        "on-primary": "#f7f7ff",
        "surface-dim": "#d3dbdd",
        "error": "#9f403d",
        "surface-container": "#ebeeef",
      },
    },
  },
  plugins: [],
};
